added account settings page
WildCodeSchool/2024-02-wns-bleu-healthcheck pull request #73
Opened 2024-08-21 15:18 UTC by pierre-castro

edited dockercompose for hotreload

2024-08-22 13:18 UTC, Scaramax requested changes

2024-08-22 13:18 UTC, Scaramax commented on backend/src/resolvers/UserResolver.ts
> +    @Arg("email") email: string, @Arg("newEmail") newEmail: string, @Arg("name") name: string,
Problème : n'importe qui peut modifier les infos de n'importe qui à partir de son email. Il faut utiliser le contexte d'authentification pour faire ça proprement

2024-08-22 14:22 UTC, pierre-castro commented on backend/src/resolvers/UserResolver.ts
> +    @Arg("email") email: string, @Arg("newEmail") newEmail: string, @Arg("name") name: string,
fixed

2024-08-22 14:22 UTC, pierre-castro commented on backend/src/resolvers/UserResolver.ts
> +      user.email = newEmail;
fixed

2024-08-23 09:09 UTC, Scaramax approved these changes
OK

2024-08-23 09:10 UTC, merged